name: 'last-green-sha'
description: 'Obtains commit hash of a last successful workflow run.'
author: 'Highnote'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  repo:
    description: 'GitHub owner and repository name. e.g. Codertocat/Hello-World'
    default: ${{ github.repository }}
    required: false
  workflow:
    description: 'Workflow name to look for.'
    default: ${{ github.workflow }}
    required: false
  branch:
    description: 'Branch name to look for.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
